config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'dynamic_pages/home'
  get 'dynamic_pages/gossip'
  get 'dynamic_pages/user'
  get '/static_pages/home', to: 'static_pages#home'
  get '/static_pages/team', to: 'static_pages#team'
  get '/static_pages/contact', to: 'static_pages#contact'
  get '/home/:id', to: 'dynamic_pages#home', as: 'home'
  get '/gossip/:id', to: 'dynamic_pages#gossip', as: 'gossip'
  get '/user/:id', to: 'dynamic_pages#user', as: 'user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip, optional: true
  belongs_to :commentable, polymorphic: true, optional: true
  belongs_to :user
  has_many :likes
  has_many :comments, as: :commentable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments
  has_many :likes
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip, optional: true
  belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :recipient_lists
end

app/models/recipient_list.rb
class RecipientList < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "RecipientList"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dynamic_pages_controller.rb
class DynamicPagesController < ApplicationController
  def home
    params[:user] = User.find(params[:id]) #POUR LA RECHERCHE EN BDD
  end
  def gossip   
    params[:gossip] = Gossip.find(params[:id])
    params[:comments] = Comment.where(gossip_id: params[:id]).all
  end
  def user
    params[:user] = User.find(params[:id])
    params[:city] = City.find(params[:user].city_id)
    params[:nb_gossips] = Gossip.where(user_id: params[:user].id).count
    params[:nb_comments] = Gossip.where(user_id: params[:user].id).count
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    params[:gossip_array] = Gossip.all
  end
  def team
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dynamic_pages/gossip.html.erb
<% content_for :title, "Gossip" %>
<!-- Affichage Stylisé du Gossip-->
<div class ='align-middle text-center'>
	<div class="card mt-5 ml-5 mr-5" style="height:200px">
	  <div class="card-body">
	    <h5 class="card-title"><%= params[:gossip].title %></h5>
	    <p class="card-title"><%= params[:gossip].created_at.strftime("%d/%m/%Y") %></p>
	    <p class="card-title">A gossip from : <%= link_to params[:gossip].user.first_name , dynamic_pages_user_path(:id => params[:gossip].user.id)%></p>
	    <p class="card-text"><%= params[:gossip].content %></p>
	  </div>
	</div>
</div>


<!-- DISPLAY DES COMMENTAIRES -->
<h1 class='text-center mt-2 mb-2'>Comments</h1>
<div class='container-fluid'>
	<div class="row">
		<% params[:comments].each do |comment| %>
			<div class="col-4 col-sm-4 col-md-4 col-lg-4 mt-5 text-center" style="width: 18rem">
			  <div class="card-body">
			    <h5 class="card-title">From : 
					    <%= link_to comment.user.first_name , dynamic_pages_user_path(:id => comment.user.id)%></h5>
				<p class="card-title"><%= comment.created_at.strftime("%d/%m/%Y") %></p>
			    <p class="card-title"><%= comment.content %></p>
			  </div>
			</div>
		<%end%>
	</div>
</div>

app/views/dynamic_pages/home.html.erb
<% content_for :title, "Home" %>

<h1>DynamicPages#home</h1>
<p>Find me in app/views/dynamic_pages/home.html.erb</p>
<h1> Hello <%= params[:user].first_name %>, bien ou bien ? </ p>

app/views/dynamic_pages/user.html.erb
<% content_for :title, "Profile" %>

<div class ='align-middle'>
	<div class="card mt-5 ml-5 mr-5" style="height:300px">
	  <div class="card-body">
	    <h5 class="card-title"><%= params[:user].first_name %> <%= params[:user].last_name %></h5>
	    <p class="card-title"><strong>Age : </strong> <%= params[:user].age %></p>
	    <p class="card-title"><strong>From : </strong><%= params[:city].name %></p>
	    <p class="card-text"> <strong>Bio:</strong><br/> <%= params[:user].description %></p>
	    <p class="card-text"> <strong>Joined The GOssip Project : </strong><%= params[:user].created_at.strftime("%d/%m/%Y") %></p>
	    <p class="card-text"> <strong>Gossips shared : </strong><%= params[:nb_gossips] %></p>
	    <p class="card-text"> <strong>Comments : </strong><%= params[:nb_comments] %></p>
	  </div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--  Font Awesome  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" crossorigin="anonymous">
    <!-- BOOTSWATCH -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/journal/bootstrap.min.css" rel="stylesheet" integrity="sha384-ciphE0NCAlD2/N6NUApXAN2dAs/vcSAOTzyE202jJx3oS8n4tAQezRgnlHqcJ59C" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- NAVBAR -->


    <nav class="navbar navbar-expand-lg navbar-dark bg-primary ">
            <%= link_to "The Gossip Project", {controller: "static_pages", action: "home"}, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", {controller: "static_pages", action: "home"}, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Add a Gossip", {controller: "static_pages", action: "home"},class: "nav-link"%>
          </li>
          <li class="nav-item active">
            <%= link_to "Team", {controller: "static_pages", action: "team"}, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", {controller: "static_pages", action: "contact"}, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% content_for :title, "Contact" %>
<!------ Include the above in your HEAD tag ---------->

<div class="container contact-form">
            <div class="contact-image">
                <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact"/>
            </div>
            <form method="post">
                <h3>Drop Us a Message</h3>
               <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" name="txtName" class="form-control" placeholder="Your Name *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="txtEmail" class="form-control" placeholder="Your Email *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="txtPhone" class="form-control" placeholder="Your Phone Number *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="submit" name="btnSubmit" class="btnContact" value="Send Message" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea name="txtMsg" class="form-control" placeholder="Your Message *" style="width: 100%; height: 150px;"></textarea>
                        </div>
                    </div>
                </div>
            </form>
</div>

app/views/static_pages/home.html.erb
<% content_for :title, "Home" %>

<!-- JUMBOTRON HERO -->

<div class="jumbotron-hero">
  <div class="container text-center" >
    <h1 class="display-4 pt-5 font-weight-bold text-dark">THE GOSSIP PROJECT</h1>
    <p class="lead pt-5 text-light ">Join our community and share your gossips</p>
    <%= link_to "Create an account and share a Gossip !", {controller: "static_pages", action: "home"}, class: "btn btn-success btn-lg mt-5 mr-4 " %>
  </div>
</div>


<!-- GOSSIPS DISPLAY -->
<div class="container-fluid">
	<div class="row">
		<% params[:gossip_array].each do |gossip| %>
		<div class= "col-4 col-sm-4 col-md-4 col-lg-4 mt-5 text-center" > 
			<div class="card" style="width: 18rem;">
			  <div class="card-body">
			    <h5 class="card-title"><%= gossip.title %></h5>
			    <p class="card-title">A gossip from : <%= link_to gossip.user.first_name , dynamic_pages_user_path(:id => gossip.user.id)%></p>
			    <%= link_to "See this Gossip", dynamic_pages_gossip_path(:id => gossip.id), class: 'btn btn-primary' %>
			  </div>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/static_pages/team.html.erb
<% content_for :title, "Team" %>

<!-- Section: Team v.1 -->
<section class="team-section text-center my-5">

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold my-5">Our amazing team</h2>
  <!-- Section description -->
  <p class="grey-text w-responsive mx-auto mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    Fugit, error amet numquam iure provident voluptate esse quasi, veritatis totam voluptas nostrum quisquam
    eum porro a pariatur veniam.</p>

  <!-- Grid row -->
  <div class="row">

    <!-- Grid column -->
    <div class="col-lg-3 col-md-6 mb-lg-0 mb-5">
      <div class="avatar mx-auto">
        <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(20).jpg" class="rounded-circle z-depth-1"
          alt="Sample avatar">
      </div>
      <h5 class="font-weight-bold mt-4 mb-3">Fanny</h5>
      <p class="text-uppercase blue-text"><strong>Graphic designer</strong></p>
      <p class="grey-text">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
        adipisci sed quia non numquam modi tempora eius.</p>
      <ul class="list-unstyled mb-0">
        <!-- Facebook -->
        <a class="p-2 fa-lg fb-ic">
          <i class="fab fa-facebook-f blue-text"> </i>
        </a>
        <!-- Twitter -->
        <a class="p-2 fa-lg tw-ic">
          <i class="fab fa-twitter blue-text"> </i>
        </a>
        <!-- Instagram -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-instagram blue-text"> </i>
        </a>
      </ul>
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-3 col-md-6 mb-lg-0 mb-5">
      <div class="avatar mx-auto">
        <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(3).jpg" class="rounded-circle z-depth-1"
          alt="Sample avatar">
      </div>
      <h5 class="font-weight-bold mt-4 mb-3">Andrei</h5>
      <p class="text-uppercase blue-text"><strong>Web developer</strong></p>
      <p class="grey-text">Sed ut perspiciatis unde omnis iste natus error sit voluptatem ipsa accusantium
        doloremque rem laudantium totam aperiam.</p>
      <ul class="list-unstyled mb-0">
        <!-- Facebook -->
        <a class="p-2 fa-lg fb-ic">
          <i class="fab fa-facebook-f blue-text"> </i>
        </a>
        <!-- Instagram -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-instagram blue-text"> </i>
        </a>
      </ul>
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-3 col-md-6 mb-md-0 mb-5">
      <div class="avatar mx-auto">
        <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(30).jpg" class="rounded-circle z-depth-1"
          alt="Sample avatar">
      </div>
      <h5 class="font-weight-bold mt-4 mb-3">Luc</h5>
      <p class="text-uppercase blue-text"><strong>K-POP artist</strong></p>
      <p class="grey-text">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
        mollit anim est fugiat nulla id eu laborum.</p>
      <ul class="list-unstyled mb-0">
        <!-- Facebook -->
        <a class="p-2 fa-lg fb-ic">
          <i class="fab fa-facebook-f blue-text"> </i>
        </a>
        <!-- Instagram -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-instagram blue-text"> </i>
        </a>
        <!-- Dribbble -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-dribbble blue-text"> </i>
        </a>
      </ul>
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-3 col-md-6">
      <div class="avatar mx-auto">
        <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(32).jpg" class="rounded-circle z-depth-1"
          alt="Sample avatar">
      </div>
      <h5 class="font-weight-bold mt-4 mb-3">Maxence</h5>
      <p class="text-uppercase blue-text"><strong>Backend developer</strong></p>
      <p class="grey-text">Perspiciatis repellendus ad odit consequuntur, eveniet earum nisi qui consectetur
        totam officia voluptates perferendis voluptatibus aut.</p>
      <ul class="list-unstyled mb-0">
        <!-- Facebook -->
        <a class="p-2 fa-lg fb-ic">
          <i class="fab fa-facebook-f blue-text"> </i>
        </a>
        <!-- Github -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-github blue-text"> </i>
        </a>
      </ul>
    </div>
    <!-- Grid column -->

  </div>
  <!-- Grid row -->

</section>
<!-- Section: Team v.1 -->